wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_05HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_06HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_07HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_08HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_09HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_10HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_11HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_12HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_13HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_14HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_15HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_16HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_17HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_18HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_19HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_20HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_21HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_22HR_UTC.tif
wget https://urbanclimate.tse.ens.titech.ac.jp/database/AHE/AH4GUC/present/AHE_SSP3_2010_07_23HR_UTC.tif
